//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planillas_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egresos_empleados
    {
        public int ID_egreso { get; set; }
        public Nullable<int> ID_tipo_egreso { get; set; }
        public Nullable<int> ID_empleado { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
