//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planillas_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_egresos
    {
        public int ID_tipo_egreso { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> ID_empresa { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
