//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planillas_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_usuario { get; set; }
        public string nombre_completo { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> ID_empresa { get; set; }
        public Nullable<int> ID_tipousuario { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Tipo_usuarios Tipo_usuarios { get; set; }
    }
}
